grid_params:
  network:
    1: 
      l1: [10, 'relu', 0.1]
      l2: [1,'linear',0]
    2:
      l1: [20, 'relu', 0.10]
      l2: [10, 'relu', 0.10]
      l3: [1,'linear',0]
  epochs: 
    - 50
    - 100
  batch_size: 
    - 32
  optimizer: 
    - 'adam'
    - 'sgd'
keras_callbacks: []
cv_params:
  n_jobs: 1
  cv: 4
  verb: 2
  scoring: 'neg_mean_absolute_error'